
-- First, let's check how many Pokemon we currently have in the catalog
-- and add more Pokemon to ensure we have at least 500 unique Pokemon

-- Add more Pokemon to the catalog to reach 500+ Pokemon
INSERT INTO public.pokemon_catalog (id, name, image, type, rarity, power_stats) VALUES
-- Generation 1 Pokemon (continuing from existing ones)
(2, 'Ivysaur', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/2.png', 'Grass/Poison', 'uncommon', '{"hp": 60, "attack": 62, "defense": 63}'),
(3, 'Venusaur', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/3.png', 'Grass/Poison', 'rare', '{"hp": 80, "attack": 82, "defense": 83}'),
(5, 'Charmeleon', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/5.png', 'Fire', 'uncommon', '{"hp": 58, "attack": 64, "defense": 58}'),
(6, 'Charizard', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/6.png', 'Fire/Flying', 'rare', '{"hp": 78, "attack": 84, "defense": 78}'),
(8, 'Wartortle', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/8.png', 'Water', 'uncommon', '{"hp": 59, "attack": 63, "defense": 80}'),
(9, 'Blastoise', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/9.png', 'Water', 'rare', '{"hp": 79, "attack": 83, "defense": 100}'),
(10, 'Caterpie', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/10.png', 'Bug', 'common', '{"hp": 45, "attack": 30, "defense": 35}'),
(11, 'Metapod', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/11.png', 'Bug', 'common', '{"hp": 50, "attack": 20, "defense": 55}'),
(12, 'Butterfree', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/12.png', 'Bug/Flying', 'uncommon', '{"hp": 60, "attack": 45, "defense": 50}'),
(13, 'Weedle', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/13.png', 'Bug/Poison', 'common', '{"hp": 40, "attack": 35, "defense": 30}'),
(14, 'Kakuna', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/14.png', 'Bug/Poison', 'common', '{"hp": 45, "attack": 25, "defense": 50}'),
(15, 'Beedrill', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/15.png', 'Bug/Poison', 'uncommon', '{"hp": 65, "attack": 90, "defense": 40}'),
(16, 'Pidgey', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/16.png', 'Normal/Flying', 'common', '{"hp": 40, "attack": 45, "defense": 40}'),
(17, 'Pidgeotto', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/17.png', 'Normal/Flying', 'uncommon', '{"hp": 63, "attack": 60, "defense": 55}'),
(18, 'Pidgeot', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/18.png', 'Normal/Flying', 'rare', '{"hp": 83, "attack": 80, "defense": 75}'),
(19, 'Rattata', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/19.png', 'Normal', 'common', '{"hp": 30, "attack": 56, "defense": 35}'),
(20, 'Raticate', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/20.png', 'Normal', 'uncommon', '{"hp": 55, "attack": 81, "defense": 60}'),
(21, 'Spearow', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/21.png', 'Normal/Flying', 'common', '{"hp": 40, "attack": 60, "defense": 30}'),
(22, 'Fearow', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/22.png', 'Normal/Flying', 'uncommon', '{"hp": 65, "attack": 90, "defense": 65}'),
(23, 'Ekans', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/23.png', 'Poison', 'common', '{"hp": 35, "attack": 60, "defense": 44}'),
(24, 'Arbok', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/24.png', 'Poison', 'uncommon', '{"hp": 60, "attack": 95, "defense": 69}'),
(26, 'Raichu', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/26.png', 'Electric', 'rare', '{"hp": 60, "attack": 90, "defense": 55}'),
(27, 'Sandshrew', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/27.png', 'Ground', 'common', '{"hp": 50, "attack": 75, "defense": 85}'),
(28, 'Sandslash', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/28.png', 'Ground', 'uncommon', '{"hp": 75, "attack": 100, "defense": 110}'),
(29, 'Nidoran♀', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/29.png', 'Poison', 'common', '{"hp": 55, "attack": 47, "defense": 52}'),
(30, 'Nidorina', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/30.png', 'Poison', 'uncommon', '{"hp": 70, "attack": 62, "defense": 67}'),
(31, 'Nidoqueen', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/31.png', 'Poison/Ground', 'rare', '{"hp": 90, "attack": 92, "defense": 87}'),
(32, 'Nidoran♂', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/32.png', 'Poison', 'common', '{"hp": 46, "attack": 57, "defense": 40}'),
(33, 'Nidorino', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/33.png', 'Poison', 'uncommon', '{"hp": 61, "attack": 72, "defense": 57}'),
(34, 'Nidoking', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/34.png', 'Poison/Ground', 'rare', '{"hp": 81, "attack": 102, "defense": 77}'),
(35, 'Clefairy', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/35.png', 'Fairy', 'uncommon', '{"hp": 70, "attack": 45, "defense": 48}'),
(36, 'Clefable', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/36.png', 'Fairy', 'rare', '{"hp": 95, "attack": 70, "defense": 73}'),
(37, 'Vulpix', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/37.png', 'Fire', 'uncommon', '{"hp": 38, "attack": 41, "defense": 40}'),
(38, 'Ninetales', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/38.png', 'Fire', 'rare', '{"hp": 73, "attack": 76, "defense": 75}'),
(39, 'Jigglypuff', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/39.png', 'Normal/Fairy', 'uncommon', '{"hp": 115, "attack": 45, "defense": 20}'),
(40, 'Wigglytuff', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/40.png', 'Normal/Fairy', 'rare', '{"hp": 140, "attack": 70, "defense": 45}'),
(41, 'Zubat', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/41.png', 'Poison/Flying', 'common', '{"hp": 40, "attack": 45, "defense": 35}'),
(42, 'Golbat', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/42.png', 'Poison/Flying', 'uncommon', '{"hp": 75, "attack": 80, "defense": 70}'),
(43, 'Oddish', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/43.png', 'Grass/Poison', 'common', '{"hp": 45, "attack": 50, "defense": 55}'),
(44, 'Gloom', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/44.png', 'Grass/Poison', 'uncommon', '{"hp": 60, "attack": 65, "defense": 70}'),
(45, 'Vileplume', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/45.png', 'Grass/Poison', 'rare', '{"hp": 75, "attack": 80, "defense": 85}'),
(46, 'Paras', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/46.png', 'Bug/Grass', 'common', '{"hp": 35, "attack": 70, "defense": 55}'),
(47, 'Parasect', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/47.png', 'Bug/Grass', 'uncommon', '{"hp": 60, "attack": 95, "defense": 80}'),
(48, 'Venonat', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/48.png', 'Bug/Poison', 'common', '{"hp": 60, "attack": 55, "defense": 50}'),
(49, 'Venomoth', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/49.png', 'Bug/Poison', 'uncommon', '{"hp": 70, "attack": 65, "defense": 60}'),
(50, 'Diglett', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/50.png', 'Ground', 'common', '{"hp": 10, "attack": 55, "defense": 25}'),
(51, 'Dugtrio', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/51.png', 'Ground', 'uncommon', '{"hp": 35, "attack": 100, "defense": 50}'),
(52, 'Meowth', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/52.png', 'Normal', 'common', '{"hp": 40, "attack": 45, "defense": 35}'),
(53, 'Persian', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/53.png', 'Normal', 'uncommon', '{"hp": 65, "attack": 70, "defense": 60}'),
(54, 'Psyduck', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/54.png', 'Water', 'common', '{"hp": 50, "attack": 52, "defense": 48}'),
(55, 'Golduck', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/55.png', 'Water', 'uncommon', '{"hp": 80, "attack": 82, "defense": 78}'),
(56, 'Mankey', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/56.png', 'Fighting', 'common', '{"hp": 40, "attack": 80, "defense": 35}'),
(57, 'Primeape', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/57.png', 'Fighting', 'uncommon', '{"hp": 65, "attack": 105, "defense": 60}'),
(58, 'Growlithe', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/58.png', 'Fire', 'uncommon', '{"hp": 55, "attack": 70, "defense": 45}'),
(59, 'Arcanine', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/59.png', 'Fire', 'rare', '{"hp": 90, "attack": 110, "defense": 80}'),
(60, 'Poliwag', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/60.png', 'Water', 'common', '{"hp": 40, "attack": 50, "defense": 40}'),
(61, 'Poliwhirl', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/61.png', 'Water', 'uncommon', '{"hp": 65, "attack": 65, "defense": 65}'),
(62, 'Poliwrath', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/62.png', 'Water/Fighting', 'rare', '{"hp": 90, "attack": 95, "defense": 95}'),
(63, 'Abra', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/63.png', 'Psychic', 'uncommon', '{"hp": 25, "attack": 20, "defense": 15}'),
(64, 'Kadabra', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/64.png', 'Psychic', 'rare', '{"hp": 40, "attack": 35, "defense": 30}'),
(65, 'Alakazam', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/65.png', 'Psychic', 'rare', '{"hp": 55, "attack": 50, "defense": 45}'),
(66, 'Machop', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/66.png', 'Fighting', 'common', '{"hp": 70, "attack": 80, "defense": 50}'),
(67, 'Machoke', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/67.png', 'Fighting', 'uncommon', '{"hp": 80, "attack": 100, "defense": 70}'),
(68, 'Machamp', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/68.png', 'Fighting', 'rare', '{"hp": 90, "attack": 130, "defense": 80}'),
(69, 'Bellsprout', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/69.png', 'Grass/Poison', 'common', '{"hp": 50, "attack": 75, "defense": 35}'),
(70, 'Weepinbell', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/70.png', 'Grass/Poison', 'uncommon', '{"hp": 65, "attack": 90, "defense": 50}'),
(71, 'Victreebel', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/71.png', 'Grass/Poison', 'rare', '{"hp": 80, "attack": 105, "defense": 65}'),
(72, 'Tentacool', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/72.png', 'Water/Poison', 'common', '{"hp": 40, "attack": 40, "defense": 35}'),
(73, 'Tentacruel', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/73.png', 'Water/Poison', 'uncommon', '{"hp": 80, "attack": 70, "defense": 65}'),
(74, 'Geodude', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/74.png', 'Rock/Ground', 'common', '{"hp": 40, "attack": 80, "defense": 100}'),
(75, 'Graveler', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/75.png', 'Rock/Ground', 'uncommon', '{"hp": 55, "attack": 95, "defense": 115}'),
(76, 'Golem', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/76.png', 'Rock/Ground', 'rare', '{"hp": 80, "attack": 120, "defense": 130}'),
(77, 'Ponyta', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/77.png', 'Fire', 'uncommon', '{"hp": 50, "attack": 85, "defense": 55}'),
(78, 'Rapidash', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/78.png', 'Fire', 'rare', '{"hp": 65, "attack": 100, "defense": 70}'),
(79, 'Slowpoke', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/79.png', 'Water/Psychic', 'common', '{"hp": 90, "attack": 65, "defense": 65}'),
(80, 'Slowbro', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/80.png', 'Water/Psychic', 'uncommon', '{"hp": 95, "attack": 75, "defense": 110}'),
(81, 'Magnemite', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/81.png', 'Electric/Steel', 'common', '{"hp": 25, "attack": 35, "defense": 70}'),
(82, 'Magneton', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/82.png', 'Electric/Steel', 'uncommon', '{"hp": 50, "attack": 60, "defense": 95}'),
(83, 'Farfetchd', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/83.png', 'Normal/Flying', 'uncommon', '{"hp": 52, "attack": 90, "defense": 55}'),
(84, 'Doduo', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/84.png', 'Normal/Flying', 'common', '{"hp": 35, "attack": 85, "defense": 45}'),
(85, 'Dodrio', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/85.png', 'Normal/Flying', 'uncommon', '{"hp": 60, "attack": 110, "defense": 70}'),
(86, 'Seel', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/86.png', 'Water', 'common', '{"hp": 65, "attack": 45, "defense": 55}'),
(87, 'Dewgong', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/87.png', 'Water/Ice', 'uncommon', '{"hp": 90, "attack": 70, "defense": 80}'),
(88, 'Grimer', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/88.png', 'Poison', 'common', '{"hp": 80, "attack": 80, "defense": 50}'),
(89, 'Muk', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/89.png', 'Poison', 'uncommon', '{"hp": 105, "attack": 105, "defense": 75}'),
(90, 'Shellder', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/90.png', 'Water', 'common', '{"hp": 30, "attack": 65, "defense": 100}'),
(91, 'Cloyster', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/91.png', 'Water/Ice', 'uncommon', '{"hp": 50, "attack": 95, "defense": 180}'),
(92, 'Gastly', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/92.png', 'Ghost/Poison', 'uncommon', '{"hp": 30, "attack": 35, "defense": 30}'),
(93, 'Haunter', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/93.png', 'Ghost/Poison', 'rare', '{"hp": 45, "attack": 50, "defense": 45}'),
(94, 'Gengar', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/94.png', 'Ghost/Poison', 'rare', '{"hp": 60, "attack": 65, "defense": 60}'),
(95, 'Onix', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/95.png', 'Rock/Ground', 'uncommon', '{"hp": 35, "attack": 45, "defense": 160}'),
(96, 'Drowzee', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/96.png', 'Psychic', 'common', '{"hp": 60, "attack": 48, "defense": 45}'),
(97, 'Hypno', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/97.png', 'Psychic', 'uncommon', '{"hp": 85, "attack": 73, "defense": 70}'),
(98, 'Krabby', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/98.png', 'Water', 'common', '{"hp": 30, "attack": 105, "defense": 90}'),
(99, 'Kingler', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/99.png', 'Water', 'uncommon', '{"hp": 55, "attack": 130, "defense": 115}'),
(100, 'Voltorb', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/100.png', 'Electric', 'common', '{"hp": 40, "attack": 30, "defense": 50}'),
(101, 'Electrode', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/101.png', 'Electric', 'uncommon', '{"hp": 60, "attack": 50, "defense": 70}'),
(102, 'Exeggcute', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/102.png', 'Grass/Psychic', 'common', '{"hp": 60, "attack": 40, "defense": 80}'),
(103, 'Exeggutor', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/103.png', 'Grass/Psychic', 'uncommon', '{"hp": 95, "attack": 95, "defense": 85}'),
(104, 'Cubone', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/104.png', 'Ground', 'common', '{"hp": 50, "attack": 50, "defense": 95}'),
(105, 'Marowak', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/105.png', 'Ground', 'uncommon', '{"hp": 60, "attack": 80, "defense": 110}'),
(106, 'Hitmonlee', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/106.png', 'Fighting', 'rare', '{"hp": 50, "attack": 120, "defense": 53}'),
(107, 'Hitmonchan', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/107.png', 'Fighting', 'rare', '{"hp": 50, "attack": 105, "defense": 79}'),
(108, 'Lickitung', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/108.png', 'Normal', 'uncommon', '{"hp": 90, "attack": 55, "defense": 75}'),
(109, 'Koffing', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/109.png', 'Poison', 'common', '{"hp": 40, "attack": 65, "defense": 95}'),
(110, 'Weezing', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/110.png', 'Poison', 'uncommon', '{"hp": 65, "attack": 90, "defense": 120}'),
(111, 'Rhyhorn', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/111.png', 'Ground/Rock', 'uncommon', '{"hp": 80, "attack": 85, "defense": 95}'),
(112, 'Rhydon', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/112.png', 'Ground/Rock', 'rare', '{"hp": 105, "attack": 130, "defense": 120}'),
(113, 'Chansey', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/113.png', 'Normal', 'rare', '{"hp": 250, "attack": 5, "defense": 5}'),
(114, 'Tangela', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/114.png', 'Grass', 'uncommon', '{"hp": 65, "attack": 55, "defense": 115}'),
(115, 'Kangaskhan', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/115.png', 'Normal', 'rare', '{"hp": 105, "attack": 95, "defense": 80}'),
(116, 'Horsea', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/116.png', 'Water', 'common', '{"hp": 30, "attack": 40, "defense": 70}'),
(117, 'Seadra', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/117.png', 'Water', 'uncommon', '{"hp": 55, "attack": 65, "defense": 95}'),
(118, 'Goldeen', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/118.png', 'Water', 'common', '{"hp": 45, "attack": 67, "defense": 60}'),
(119, 'Seaking', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/119.png', 'Water', 'uncommon', '{"hp": 80, "attack": 92, "defense": 65}'),
(120, 'Staryu', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/120.png', 'Water', 'common', '{"hp": 30, "attack": 45, "defense": 55}'),
(121, 'Starmie', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/121.png', 'Water/Psychic', 'uncommon', '{"hp": 60, "attack": 75, "defense": 85}'),
(122, 'Mr. Mime', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/122.png', 'Psychic/Fairy', 'rare', '{"hp": 40, "attack": 45, "defense": 65}'),
(123, 'Scyther', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/123.png', 'Bug/Flying', 'rare', '{"hp": 70, "attack": 110, "defense": 80}'),
(124, 'Jynx', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/124.png', 'Ice/Psychic', 'rare', '{"hp": 65, "attack": 50, "defense": 35}'),
(125, 'Electabuzz', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/125.png', 'Electric', 'rare', '{"hp": 65, "attack": 83, "defense": 57}'),
(126, 'Magmar', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/126.png', 'Fire', 'rare', '{"hp": 65, "attack": 95, "defense": 57}'),
(127, 'Pinsir', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/127.png', 'Bug', 'rare', '{"hp": 65, "attack": 125, "defense": 100}'),
(128, 'Tauros', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/128.png', 'Normal', 'rare', '{"hp": 75, "attack": 100, "defense": 95}'),
(129, 'Magikarp', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/129.png', 'Water', 'common', '{"hp": 20, "attack": 10, "defense": 55}'),
(130, 'Gyarados', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/130.png', 'Water/Flying', 'rare', '{"hp": 95, "attack": 125, "defense": 79}'),
(131, 'Lapras', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/131.png', 'Water/Ice', 'rare', '{"hp": 130, "attack": 85, "defense": 80}'),
(132, 'Ditto', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/132.png', 'Normal', 'rare', '{"hp": 48, "attack": 48, "defense": 48}'),
(133, 'Eevee', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/133.png', 'Normal', 'rare', '{"hp": 55, "attack": 55, "defense": 50}'),
(134, 'Vaporeon', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/134.png', 'Water', 'rare', '{"hp": 130, "attack": 65, "defense": 60}'),
(135, 'Jolteon', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/135.png', 'Electric', 'rare', '{"hp": 65, "attack": 65, "defense": 60}'),
(136, 'Flareon', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/136.png', 'Fire', 'rare', '{"hp": 65, "attack": 130, "defense": 60}'),
(137, 'Porygon', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/137.png', 'Normal', 'rare', '{"hp": 65, "attack": 60, "defense": 70}'),
(138, 'Omanyte', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/138.png', 'Rock/Water', 'rare', '{"hp": 35, "attack": 40, "defense": 100}'),
(139, 'Omastar', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/139.png', 'Rock/Water', 'rare', '{"hp": 70, "attack": 60, "defense": 125}'),
(140, 'Kabuto', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/140.png', 'Rock/Water', 'rare', '{"hp": 30, "attack": 80, "defense": 90}'),
(141, 'Kabutops', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/141.png', 'Rock/Water', 'rare', '{"hp": 60, "attack": 115, "defense": 105}'),
(142, 'Aerodactyl', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/142.png', 'Rock/Flying', 'rare', '{"hp": 80, "attack": 105, "defense": 65}'),
(143, 'Snorlax', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/143.png', 'Normal', 'rare', '{"hp": 160, "attack": 110, "defense": 65}'),
(144, 'Articuno', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/144.png', 'Ice/Flying', 'legendary', '{"hp": 90, "attack": 85, "defense": 100}'),
(145, 'Zapdos', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/145.png', 'Electric/Flying', 'legendary', '{"hp": 90, "attack": 90, "defense": 85}'),
(146, 'Moltres', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/146.png', 'Fire/Flying', 'legendary', '{"hp": 90, "attack": 100, "defense": 90}'),
(147, 'Dratini', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/147.png', 'Dragon', 'rare', '{"hp": 41, "attack": 64, "defense": 45}'),
(148, 'Dragonair', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/148.png', 'Dragon', 'rare', '{"hp": 61, "attack": 84, "defense": 65}'),
(149, 'Dragonite', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/149.png', 'Dragon/Flying', 'rare', '{"hp": 91, "attack": 134, "defense": 95}'),
(151, 'Mew', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/151.png', 'Psychic', 'legendary', '{"hp": 100, "attack": 100, "defense": 100}')
ON CONFLICT (id) DO NOTHING;

-- Continue adding Generation 2 Pokemon
INSERT INTO public.pokemon_catalog (id, name, image, type, rarity, power_stats) VALUES
(152, 'Chikorita', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/152.png', 'Grass', 'uncommon', '{"hp": 45, "attack": 49, "defense": 65}'),
(153, 'Bayleef', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/153.png', 'Grass', 'uncommon', '{"hp": 60, "attack": 62, "defense": 80}'),
(154, 'Meganium', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/154.png', 'Grass', 'rare', '{"hp": 80, "attack": 82, "defense": 100}'),
(155, 'Cyndaquil', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/155.png', 'Fire', 'uncommon', '{"hp": 39, "attack": 52, "defense": 43}'),
(156, 'Quilava', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/156.png', 'Fire', 'uncommon', '{"hp": 58, "attack": 64, "defense": 58}'),
(157, 'Typhlosion', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/157.png', 'Fire', 'rare', '{"hp": 78, "attack": 84, "defense": 78}'),
(158, 'Totodile', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/158.png', 'Water', 'uncommon', '{"hp": 50, "attack": 65, "defense": 64}'),
(159, 'Croconaw', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/159.png', 'Water', 'uncommon', '{"hp": 65, "attack": 80, "defense": 80}'),
(160, 'Feraligatr', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/160.png', 'Water', 'rare', '{"hp": 85, "attack": 105, "defense": 100}'),
(161, 'Sentret', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/161.png', 'Normal', 'common', '{"hp": 35, "attack": 46, "defense": 34}'),
(162, 'Furret', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/162.png', 'Normal', 'uncommon', '{"hp": 85, "attack": 76, "defense": 64}'),
(163, 'Hoothoot', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/163.png', 'Normal/Flying', 'common', '{"hp": 60, "attack": 30, "defense": 30}'),
(164, 'Noctowl', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/164.png', 'Normal/Flying', 'uncommon', '{"hp": 100, "attack": 50, "defense": 50}'),
(165, 'Ledyba', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/165.png', 'Bug/Flying', 'common', '{"hp": 40, "attack": 20, "defense": 30}'),
(166, 'Ledian', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/166.png', 'Bug/Flying', 'uncommon', '{"hp": 55, "attack": 35, "defense": 50}'),
(167, 'Spinarak', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/167.png', 'Bug/Poison', 'common', '{"hp": 40, "attack": 60, "defense": 40}'),
(168, 'Ariados', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/168.png', 'Bug/Poison', 'uncommon', '{"hp": 70, "attack": 90, "defense": 70}'),
(169, 'Crobat', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/169.png', 'Poison/Flying', 'rare', '{"hp": 85, "attack": 90, "defense": 80}'),
(170, 'Chinchou', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/170.png', 'Water/Electric', 'common', '{"hp": 75, "attack": 38, "defense": 38}'),
(171, 'Lanturn', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/171.png', 'Water/Electric', 'uncommon', '{"hp": 125, "attack": 58, "defense": 58}'),
(172, 'Pichu', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/172.png', 'Electric', 'uncommon', '{"hp": 20, "attack": 40, "defense": 15}'),
(173, 'Cleffa', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/173.png', 'Fairy', 'uncommon', '{"hp": 50, "attack": 25, "defense": 28}'),
(174, 'Igglybuff', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/174.png', 'Normal/Fairy', 'uncommon', '{"hp": 90, "attack": 30, "defense": 15}'),
(175, 'Togepi', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/175.png', 'Fairy', 'rare', '{"hp": 35, "attack": 20, "defense": 65}'),
(176, 'Togetic', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/176.png', 'Fairy/Flying', 'rare', '{"hp": 55, "attack": 40, "defense": 85}'),
(177, 'Natu', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/177.png', 'Psychic/Flying', 'common', '{"hp": 40, "attack": 50, "defense": 45}'),
(178, 'Xatu', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/178.png', 'Psychic/Flying', 'uncommon', '{"hp": 65, "attack": 75, "defense": 70}'),
(179, 'Mareep', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/179.png', 'Electric', 'common', '{"hp": 55, "attack": 40, "defense": 40}'),
(180, 'Flaaffy', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/180.png', 'Electric', 'uncommon', '{"hp": 70, "attack": 55, "defense": 55}'),
(181, 'Ampharos', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/181.png', 'Electric', 'rare', '{"hp": 90, "attack": 75, "defense": 85}'),
(182, 'Bellossom', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/182.png', 'Grass', 'rare', '{"hp": 75, "attack": 80, "defense": 95}'),
(183, 'Marill', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/183.png', 'Water/Fairy', 'common', '{"hp": 70, "attack": 20, "defense": 50}'),
(184, 'Azumarill', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/184.png', 'Water/Fairy', 'uncommon', '{"hp": 100, "attack": 50, "defense": 80}'),
(185, 'Sudowoodo', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/185.png', 'Rock', 'uncommon', '{"hp": 70, "attack": 100, "defense": 115}'),
(186, 'Politoed', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/186.png', 'Water', 'rare', '{"hp": 90, "attack": 75, "defense": 75}'),
(187, 'Hoppip', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/187.png', 'Grass/Flying', 'common', '{"hp": 35, "attack": 35, "defense": 40}'),
(188, 'Skiploom', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/188.png', 'Grass/Flying', 'uncommon', '{"hp": 55, "attack": 45, "defense": 50}'),
(189, 'Jumpluff', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/189.png', 'Grass/Flying', 'uncommon', '{"hp": 75, "attack": 55, "defense": 70}'),
(190, 'Aipom', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/190.png', 'Normal', 'uncommon', '{"hp": 55, "attack": 70, "defense": 55}'),
(191, 'Sunkern', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/191.png', 'Grass', 'common', '{"hp": 30, "attack": 30, "defense": 30}'),
(192, 'Sunflora', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/192.png', 'Grass', 'uncommon', '{"hp": 75, "attack": 75, "defense": 55}'),
(193, 'Yanma', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/193.png', 'Bug/Flying', 'uncommon', '{"hp": 65, "attack": 65, "defense": 45}'),
(194, 'Wooper', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/194.png', 'Water/Ground', 'common', '{"hp": 55, "attack": 45, "defense": 45}'),
(195, 'Quagsire', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/195.png', 'Water/Ground', 'uncommon', '{"hp": 95, "attack": 85, "defense": 85}'),
(196, 'Espeon', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/196.png', 'Psychic', 'rare', '{"hp": 65, "attack": 65, "defense": 60}'),
(197, 'Umbreon', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/197.png', 'Dark', 'rare', '{"hp": 95, "attack": 65, "defense": 110}'),
(198, 'Murkrow', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/198.png', 'Dark/Flying', 'uncommon', '{"hp": 60, "attack": 85, "defense": 42}'),
(199, 'Slowking', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/199.png', 'Water/Psychic', 'rare', '{"hp": 95, "attack": 75, "defense": 80}'),
(200, 'Misdreavus', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/200.png', 'Ghost', 'uncommon', '{"hp": 60, "attack": 60, "defense": 60}')
ON CONFLICT (id) DO NOTHING;

-- Continue with more Pokemon to reach 500+ total
-- Adding Generation 3 Pokemon (Ruby/Sapphire)
INSERT INTO public.pokemon_catalog (id, name, image, type, rarity, power_stats) VALUES
(252, 'Treecko', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/252.png', 'Grass', 'uncommon', '{"hp": 40, "attack": 45, "defense": 35}'),
(253, 'Grovyle', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/253.png', 'Grass', 'uncommon', '{"hp": 50, "attack": 65, "defense": 45}'),
(254, 'Sceptile', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/254.png', 'Grass', 'rare', '{"hp": 70, "attack": 85, "defense": 65}'),
(255, 'Torchic', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/255.png', 'Fire', 'uncommon', '{"hp": 45, "attack": 60, "defense": 40}'),
(256, 'Combusken', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/256.png', 'Fire/Fighting', 'uncommon', '{"hp": 60, "attack": 85, "defense": 60}'),
(257, 'Blaziken', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/257.png', 'Fire/Fighting', 'rare', '{"hp": 80, "attack": 120, "defense": 70}'),
(258, 'Mudkip', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/258.png', 'Water', 'uncommon', '{"hp": 50, "attack": 70, "defense": 50}'),
(259, 'Marshtomp', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/259.png', 'Water/Ground', 'uncommon', '{"hp": 70, "attack": 85, "defense": 70}'),
(260, 'Swampert', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/260.png', 'Water/Ground', 'rare', '{"hp": 100, "attack": 110, "defense": 90}'),
(261, 'Poochyena', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/261.png', 'Dark', 'common', '{"hp": 35, "attack": 55, "defense": 35}'),
(262, 'Mightyena', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/262.png', 'Dark', 'uncommon', '{"hp": 70, "attack": 90, "defense": 70}'),
(263, 'Zigzagoon', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/263.png', 'Normal', 'common', '{"hp": 38, "attack": 30, "defense": 41}'),
(264, 'Linoone', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/264.png', 'Normal', 'uncommon', '{"hp": 78, "attack": 70, "defense": 61}'),
(265, 'Wurmple', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/265.png', 'Bug', 'common', '{"hp": 45, "attack": 45, "defense": 35}'),
(266, 'Silcoon', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/266.png', 'Bug', 'common', '{"hp": 50, "attack": 35, "defense": 55}'),
(267, 'Beautifly', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/267.png', 'Bug/Flying', 'uncommon', '{"hp": 60, "attack": 70, "defense": 50}'),
(268, 'Cascoon', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/268.png', 'Bug', 'common', '{"hp": 50, "attack": 35, "defense": 55}'),
(269, 'Dustox', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/269.png', 'Bug/Poison', 'uncommon', '{"hp": 60, "attack": 50, "defense": 70}'),
(270, 'Lotad', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/270.png', 'Water/Grass', 'common', '{"hp": 40, "attack": 30, "defense": 30}'),
(271, 'Lombre', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/271.png', 'Water/Grass', 'uncommon', '{"hp": 60, "attack": 50, "defense": 50}'),
(272, 'Ludicolo', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/272.png', 'Water/Grass', 'rare', '{"hp": 80, "attack": 70, "defense": 70}'),
(273, 'Seedot', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/273.png', 'Grass', 'common', '{"hp": 40, "attack": 40, "defense": 50}'),
(274, 'Nuzleaf', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/274.png', 'Grass/Dark', 'uncommon', '{"hp": 70, "attack": 70, "defense": 40}'),
(275, 'Shiftry', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/275.png', 'Grass/Dark', 'rare', '{"hp": 90, "attack": 100, "defense": 60}'),
(276, 'Taillow', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/276.png', 'Normal/Flying', 'common', '{"hp": 40, "attack": 55, "defense": 30}'),
(277, 'Swellow', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/277.png', 'Normal/Flying', 'uncommon', '{"hp": 60, "attack": 85, "defense": 60}'),
(278, 'Wingull', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/278.png', 'Water/Flying', 'common', '{"hp": 40, "attack": 30, "defense": 30}'),
(279, 'Pelipper', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/279.png', 'Water/Flying', 'uncommon', '{"hp": 60, "attack": 50, "defense": 100}'),
(280, 'Ralts', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/280.png', 'Psychic/Fairy', 'uncommon', '{"hp": 28, "attack": 25, "defense": 25}'),
(281, 'Kirlia', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/281.png', 'Psychic/Fairy', 'rare', '{"hp": 38, "attack": 35, "defense": 35}'),
(282, 'Gardevoir', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/282.png', 'Psychic/Fairy', 'rare', '{"hp": 68, "attack": 65, "defense": 65}'),
(283, 'Surskit', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/283.png', 'Bug/Water', 'common', '{"hp": 40, "attack": 30, "defense": 32}'),
(284, 'Masquerain', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/284.png', 'Bug/Flying', 'uncommon', '{"hp": 70, "attack": 60, "defense": 62}'),
(285, 'Shroomish', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/285.png', 'Grass', 'common', '{"hp": 60, "attack": 40, "defense": 60}'),
(286, 'Breloom', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/286.png', 'Grass/Fighting', 'rare', '{"hp": 60, "attack": 130, "defense": 80}'),
(287, 'Slakoth', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/287.png', 'Normal', 'common', '{"hp": 60, "attack": 60, "defense": 60}'),
(288, 'Vigoroth', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/288.png', 'Normal', 'uncommon', '{"hp": 80, "attack": 80, "defense": 80}'),
(289, 'Slaking', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/289.png', 'Normal', 'rare', '{"hp": 150, "attack": 160, "defense": 100}'),
(290, 'Nincada', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/290.png', 'Bug/Ground', 'common', '{"hp": 31, "attack": 45, "defense": 90}'),
(291, 'Ninjask', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/291.png', 'Bug/Flying', 'rare', '{"hp": 61, "attack": 90, "defense": 45}'),
(292, 'Shedinja', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/292.png', 'Bug/Ghost', 'rare', '{"hp": 1, "attack": 90, "defense": 45}'),
(293, 'Whismur', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/293.png', 'Normal', 'common', '{"hp": 64, "attack": 51, "defense": 23}'),
(294, 'Loudred', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/294.png', 'Normal', 'uncommon', '{"hp": 84, "attack": 71, "defense": 43}'),
(295, 'Exploud', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/295.png', 'Normal', 'rare', '{"hp": 104, "attack": 91, "defense": 63}'),
(296, 'Makuhita', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/296.png', 'Fighting', 'common', '{"hp": 72, "attack": 60, "defense": 30}'),
(297, 'Hariyama', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/297.png', 'Fighting', 'uncommon', '{"hp": 144, "attack": 120, "defense": 60}'),
(298, 'Azurill', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/298.png', 'Normal/Fairy', 'uncommon', '{"hp": 50, "attack": 20, "defense": 40}'),
(299, 'Nosepass', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/299.png', 'Rock', 'uncommon', '{"hp": 30, "attack": 45, "defense": 135}'),
(300, 'Skitty', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/300.png', 'Normal', 'common', '{"hp": 50, "attack": 45, "defense": 45}'),
(301, 'Delcatty', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/301.png', 'Normal', 'uncommon', '{"hp": 70, "attack": 65, "defense": 65}'),
(302, 'Sableye', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/302.png', 'Dark/Ghost', 'rare', '{"hp": 50, "attack": 75, "defense": 75}'),
(303, 'Mawile', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/303.png', 'Steel/Fairy', 'rare', '{"hp": 50, "attack": 85, "defense": 85}'),
(304, 'Aron', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/304.png', 'Steel/Rock', 'common', '{"hp": 50, "attack": 70, "defense": 100}'),
(305, 'Lairon', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/305.png', 'Steel/Rock', 'uncommon', '{"hp": 60, "attack": 90, "defense": 140}'),
(306, 'Aggron', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/306.png', 'Steel/Rock', 'rare', '{"hp": 70, "attack": 110, "defense": 180}'),
(307, 'Meditite', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/307.png', 'Fighting/Psychic', 'common', '{"hp": 30, "attack": 40, "defense": 55}'),
(308, 'Medicham', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/308.png', 'Fighting/Psychic', 'uncommon', '{"hp": 60, "attack": 60, "defense": 75}'),
(309, 'Electrike', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/309.png', 'Electric', 'common', '{"hp": 40, "attack": 45, "defense": 40}'),
(310, 'Manectric', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/310.png', 'Electric', 'uncommon', '{"hp": 70, "attack": 75, "defense": 60}'),
(311, 'Plusle', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/311.png', 'Electric', 'uncommon', '{"hp": 60, "attack": 50, "defense": 40}'),
(312, 'Minun', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/312.png', 'Electric', 'uncommon', '{"hp": 60, "attack": 40, "defense": 50}'),
(313, 'Volbeat', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/313.png', 'Bug', 'uncommon', '{"hp": 65, "attack": 73, "defense": 75}'),
(314, 'Illumise', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/314.png', 'Bug', 'uncommon', '{"hp": 65, "attack": 47, "defense": 75}'),
(315, 'Roselia', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/315.png', 'Grass/Poison', 'uncommon', '{"hp": 50, "attack": 60, "defense": 45}'),
(316, 'Gulpin', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/316.png', 'Poison', 'common', '{"hp": 70, "attack": 43, "defense": 53}'),
(317, 'Swalot', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/317.png', 'Poison', 'uncommon', '{"hp": 100, "attack": 73, "defense": 83}'),
(318, 'Carvanha', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/318.png', 'Water/Dark', 'common', '{"hp": 45, "attack": 90, "defense": 20}'),
(319, 'Sharpedo', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/319.png', 'Water/Dark', 'uncommon', '{"hp": 70, "attack": 120, "defense": 40}'),
(320, 'Wailmer', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/320.png', 'Water', 'common', '{"hp": 130, "attack": 70, "defense": 35}'),
(321, 'Wailord', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/321.png', 'Water', 'uncommon', '{"hp": 170, "attack": 90, "defense": 45}'),
(322, 'Numel', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/322.png', 'Fire/Ground', 'common', '{"hp": 60, "attack": 60, "defense": 40}'),
(323, 'Camerupt', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/323.png', 'Fire/Ground', 'uncommon', '{"hp": 70, "attack": 100, "defense": 70}'),
(324, 'Torkoal', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/324.png', 'Fire', 'uncommon', '{"hp": 70, "attack": 85, "defense": 140}'),
(325, 'Spoink', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/325.png', 'Psychic', 'common', '{"hp": 60, "attack": 25, "defense": 35}'),
(326, 'Grumpig', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/326.png', 'Psychic', 'uncommon', '{"hp": 80, "attack": 45, "defense": 65}'),
(327, 'Spinda', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/327.png', 'Normal', 'uncommon', '{"hp": 60, "attack": 60, "defense": 60}'),
(328, 'Trapinch', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/328.png', 'Ground', 'common', '{"hp": 45, "attack": 100, "defense": 45}'),
(329, 'Vibrava', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/329.png', 'Ground/Dragon', 'uncommon', '{"hp": 50, "attack": 70, "defense": 50}'),
(330, 'Flygon', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/330.png', 'Ground/Dragon', 'rare', '{"hp": 80, "attack": 100, "defense": 80}'),
(331, 'Cacnea', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/331.png', 'Grass', 'common', '{"hp": 50, "attack": 85, "defense": 40}'),
(332, 'Cacturne', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/332.png', 'Grass/Dark', 'uncommon', '{"hp": 70, "attack": 115, "defense": 60}'),
(333, 'Swablu', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/333.png', 'Normal/Flying', 'common', '{"hp": 45, "attack": 40, "defense": 60}'),
(334, 'Altaria', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/334.png', 'Dragon/Flying', 'rare', '{"hp": 75, "attack": 70, "defense": 90}'),
(335, 'Zangoose', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/335.png', 'Normal', 'uncommon', '{"hp": 73, "attack": 115, "defense": 60}'),
(336, 'Seviper', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/336.png', 'Poison', 'uncommon', '{"hp": 73, "attack": 100, "defense": 60}'),
(337, 'Lunatone', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/337.png', 'Rock/Psychic', 'uncommon', '{"hp": 90, "attack": 55, "defense": 65}'),
(338, 'Solrock', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/338.png', 'Rock/Psychic', 'uncommon', '{"hp": 90, "attack": 95, "defense": 85}'),
(339, 'Barboach', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/339.png', 'Water/Ground', 'common', '{"hp": 50, "attack": 48, "defense": 43}'),
(340, 'Whiscash', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/340.png', 'Water/Ground', 'uncommon', '{"hp": 110, "attack": 78, "defense": 73}'),
(341, 'Corphish', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/341.png', 'Water', 'common', '{"hp": 43, "attack": 80, "defense": 65}'),
(342, 'Crawdaunt', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/342.png', 'Water/Dark', 'uncommon', '{"hp": 63, "attack": 120, "defense": 85}'),
(343, 'Baltoy', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/343.png', 'Ground/Psychic', 'common', '{"hp": 40, "attack": 40, "defense": 55}'),
(344, 'Claydol', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/344.png', 'Ground/Psychic', 'uncommon', '{"hp": 60, "attack": 70, "defense": 105}'),
(345, 'Lileep', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/345.png', 'Rock/Grass', 'rare', '{"hp": 66, "attack": 41, "defense": 77}'),
(346, 'Cradily', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/346.png', 'Rock/Grass', 'rare', '{"hp": 86, "attack": 81, "defense": 97}'),
(347, 'Anorith', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/347.png', 'Rock/Bug', 'rare', '{"hp": 45, "attack": 95, "defense": 50}'),
(348, 'Armaldo', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/348.png', 'Rock/Bug', 'rare', '{"hp": 75, "attack": 125, "defense": 100}'),
(349, 'Feebas', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/349.png', 'Water', 'common', '{"hp": 20, "attack": 15, "defense": 20}'),
(350, 'Milotic', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/350.png', 'Water', 'rare', '{"hp": 95, "attack": 60, "defense": 79}'),
(351, 'Castform', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/351.png', 'Normal', 'rare', '{"hp": 70, "attack": 70, "defense": 70}'),
(352, 'Kecleon', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/352.png', 'Normal', 'uncommon', '{"hp": 60, "attack": 90, "defense": 70}'),
(353, 'Shuppet', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/353.png', 'Ghost', 'common', '{"hp": 44, "attack": 75, "defense": 35}'),
(354, 'Banette', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/354.png', 'Ghost', 'uncommon', '{"hp": 64, "attack": 115, "defense": 65}'),
(355, 'Duskull', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/355.png', 'Ghost', 'common', '{"hp": 20, "attack": 40, "defense": 90}'),
(356, 'Dusclops', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/356.png', 'Ghost', 'uncommon', '{"hp": 40, "attack": 70, "defense": 130}'),
(357, 'Tropius', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/357.png', 'Grass/Flying', 'uncommon', '{"hp": 99, "attack": 68, "defense": 83}'),
(358, 'Chimecho', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/358.png', 'Psychic', 'uncommon', '{"hp": 75, "attack": 50, "defense": 80}'),
(359, 'Absol', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/359.png', 'Dark', 'rare', '{"hp": 65, "attack": 130, "defense": 60}'),
(360, 'Wynaut', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/360.png', 'Psychic', 'uncommon', '{"hp": 95, "attack": 23, "defense": 48}'),
(361, 'Snorunt', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/361.png', 'Ice', 'common', '{"hp": 50, "attack": 50, "defense": 50}'),
(362, 'Glalie', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/362.png', 'Ice', 'uncommon', '{"hp": 80, "attack": 80, "defense": 80}'),
(363, 'Spheal', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/363.png', 'Ice/Water', 'common', '{"hp": 70, "attack": 40, "defense": 50}'),
(364, 'Sealeo', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/364.png', 'Ice/Water', 'uncommon', '{"hp": 90, "attack": 60, "defense": 70}'),
(365, 'Walrein', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/365.png', 'Ice/Water', 'rare', '{"hp": 110, "attack": 80, "defense": 90}'),
(366, 'Clamperl', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/366.png', 'Water', 'common', '{"hp": 35, "attack": 64, "defense": 85}'),
(367, 'Huntail', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/367.png', 'Water', 'uncommon', '{"hp": 55, "attack": 104, "defense": 105}'),
(368, 'Gorebyss', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/368.png', 'Water', 'uncommon', '{"hp": 55, "attack": 84, "defense": 105}'),
(369, 'Relicanth', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/369.png', 'Water/Rock', 'uncommon', '{"hp": 100, "attack": 90, "defense": 130}'),
(370, 'Luvdisc', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/370.png', 'Water', 'common', '{"hp": 43, "attack": 30, "defense": 55}'),
(371, 'Bagon', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/371.png', 'Dragon', 'rare', '{"hp": 45, "attack": 75, "defense": 60}'),
(372, 'Shelgon', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/372.png', 'Dragon', 'rare', '{"hp": 65, "attack": 95, "defense": 100}'),
(373, 'Salamence', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/373.png', 'Dragon/Flying', 'rare', '{"hp": 95, "attack": 135, "defense": 80}'),
(374, 'Beldum', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/374.png', 'Steel/Psychic', 'rare', '{"hp": 40, "attack": 55, "defense": 80}'),
(375, 'Metang', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/375.png', 'Steel/Psychic', 'rare', '{"hp": 60, "attack": 75, "defense": 100}'),
(376, 'Metagross', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/376.png', 'Steel/Psychic', 'rare', '{"hp": 80, "attack": 135, "defense": 130}'),
(377, 'Regirock', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/377.png', 'Rock', 'legendary', '{"hp": 80, "attack": 100, "defense": 200}'),
(378, 'Regice', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/378.png', 'Ice', 'legendary', '{"hp": 80, "attack": 50, "defense": 100}'),
(379, 'Registeel', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/379.png', 'Steel', 'legendary', '{"hp": 80, "attack": 75, "defense": 150}'),
(380, 'Latias', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/380.png', 'Dragon/Psychic', 'legendary', '{"hp": 80, "attack": 80, "defense": 90}'),
(381, 'Latios', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/381.png', 'Dragon/Psychic', 'legendary', '{"hp": 80, "attack": 90, "defense": 80}'),
(382, 'Kyogre', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/382.png', 'Water', 'legendary', '{"hp": 100, "attack": 100, "defense": 90}'),
(383, 'Groudon', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/383.png', 'Ground', 'legendary', '{"hp": 100, "attack": 150, "defense": 140}'),
(384, 'Rayquaza', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/384.png', 'Dragon/Flying', 'legendary', '{"hp": 105, "attack": 150, "defense": 90}'),
(385, 'Jirachi', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/385.png', 'Steel/Psychic', 'legendary', '{"hp": 100, "attack": 100, "defense": 100}'),
(386, 'Deoxys', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/386.png', 'Psychic', 'legendary', '{"hp": 50, "attack": 150, "defense": 50}')
ON CONFLICT (id) DO NOTHING;

-- Continue with Generation 4 Pokemon (Diamond/Pearl) to reach 500+
INSERT INTO public.pokemon_catalog (id, name, image, type, rarity, power_stats) VALUES
(387, 'Turtwig', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/387.png', 'Grass', 'uncommon', '{"hp": 55, "attack": 68, "defense": 64}'),
(388, 'Grotle', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/388.png', 'Grass', 'uncommon', '{"hp": 75, "attack": 89, "defense": 85}'),
(389, 'Torterra', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/389.png', 'Grass/Ground', 'rare', '{"hp": 95, "attack": 109, "defense": 105}'),
(390, 'Chimchar', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/390.png', 'Fire', 'uncommon', '{"hp": 44, "attack": 58, "defense": 44}'),
(391, 'Monferno', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/391.png', 'Fire/Fighting', 'uncommon', '{"hp": 64, "attack": 78, "defense": 52}'),
(392, 'Infernape', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/392.png', 'Fire/Fighting', 'rare', '{"hp": 76, "attack": 104, "defense": 71}'),
(393, 'Piplup', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/393.png', 'Water', 'uncommon', '{"hp": 53, "attack": 51, "defense": 53}'),
(394, 'Prinplup', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/394.png', 'Water', 'uncommon', '{"hp": 64, "attack": 66, "defense": 68}'),
(395, 'Empoleon', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/395.png', 'Water/Steel', 'rare', '{"hp": 84, "attack": 86, "defense": 88}'),
(396, 'Starly', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/396.png', 'Normal/Flying', 'common', '{"hp": 40, "attack": 55, "defense": 30}'),
(397, 'Staravia', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/397.png', 'Normal/Flying', 'uncommon', '{"hp": 55, "attack": 75, "defense": 50}'),
(398, 'Staraptor', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/398.png', 'Normal/Flying', 'rare', '{"hp": 85, "attack": 120, "defense": 70}'),
(399, 'Bidoof', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/399.png', 'Normal', 'common', '{"hp": 59, "attack": 45, "defense": 40}'),
(400, 'Bibarel', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/400.png', 'Normal/Water', 'uncommon', '{"hp": 79, "attack": 85, "defense": 60}'),
(401, 'Kricketot', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/401.png', 'Bug', 'common', '{"hp": 37, "attack": 25, "defense": 41}'),
(402, 'Kricketune', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/402.png', 'Bug', 'uncommon', '{"hp": 77, "attack": 85, "defense": 51}'),
(403, 'Shinx', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/403.png', 'Electric', 'common', '{"hp": 45, "attack": 65, "defense": 34}'),
(404, 'Luxio', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/404.png', 'Electric', 'uncommon', '{"hp": 60, "attack": 85, "defense": 49}'),
(405, 'Luxray', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/405.png', 'Electric', 'rare', '{"hp": 80, "attack": 120, "defense": 79}'),
(406, 'Budew', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/406.png', 'Grass/Poison', 'common', '{"hp": 40, "attack": 30, "defense": 35}'),
(407, 'Roserade', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/407.png', 'Grass/Poison', 'rare', '{"hp": 60, "attack": 70, "defense": 65}'),
(408, 'Cranidos', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/408.png', 'Rock', 'rare', '{"hp": 67, "attack": 125, "defense": 40}'),
(409, 'Rampardos', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/409.png', 'Rock', 'rare', '{"hp": 97, "attack": 165, "defense": 60}'),
(410, 'Shieldon', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/410.png', 'Rock/Steel', 'rare', '{"hp": 30, "attack": 42, "defense": 118}'),
(411, 'Bastiodon', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/411.png', 'Rock/Steel', 'rare', '{"hp": 60, "attack": 52, "defense": 168}'),
(412, 'Burmy', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/412.png', 'Bug', 'common', '{"hp": 40, "attack": 29, "defense": 45}'),
(413, 'Wormadam', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/413.png', 'Bug/Grass', 'uncommon', '{"hp": 60, "attack": 59, "defense": 85}'),
(414, 'Mothim', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/414.png', 'Bug/Flying', 'uncommon', '{"hp": 70, "attack": 94, "defense": 50}'),
(415, 'Combee', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/415.png', 'Bug/Flying', 'common', '{"hp": 30, "attack": 30, "defense": 42}'),
(416, 'Vespiquen', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/416.png', 'Bug/Flying', 'rare', '{"hp": 70, "attack": 80, "defense": 102}'),
(417, 'Pachirisu', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/417.png', 'Electric', 'uncommon', '{"hp": 60, "attack": 45, "defense": 70}'),
(418, 'Buizel', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/418.png', 'Water', 'common', '{"hp": 55, "attack": 65, "defense": 35}'),
(419, 'Floatzel', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/419.png', 'Water', 'uncommon', '{"hp": 85, "attack": 105, "defense": 55}'),
(420, 'Cherubi', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/420.png', 'Grass', 'common', '{"hp": 45, "attack": 35, "defense": 45}'),
(421, 'Cherrim', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/421.png', 'Grass', 'uncommon', '{"hp": 70, "attack": 60, "defense": 70}'),
(422, 'Shellos', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/422.png', 'Water', 'common', '{"hp": 76, "attack": 48, "defense": 48}'),
(423, 'Gastrodon', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/423.png', 'Water/Ground', 'uncommon', '{"hp": 111, "attack": 83, "defense": 68}'),
(424, 'Ambipom', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/424.png', 'Normal', 'uncommon', '{"hp": 75, "attack": 100, "defense": 66}'),
(425, 'Drifloon', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/425.png', 'Ghost/Flying', 'common', '{"hp": 90, "attack": 50, "defense": 34}'),
(426, 'Drifblim', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/426.png', 'Ghost/Flying', 'uncommon', '{"hp": 150, "attack": 80, "defense": 44}'),
(427, 'Buneary', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/427.png', 'Normal', 'common', '{"hp": 55, "attack": 66, "defense": 44}'),
(428, 'Lopunny', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/428.png', 'Normal', 'uncommon', '{"hp": 65, "attack": 76, "defense": 84}'),
(429, 'Mismagius', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/429.png', 'Ghost', 'rare', '{"hp": 60, "attack": 60, "defense": 60}'),
(430, 'Honchkrow', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/430.png', 'Dark/Flying', 'rare', '{"hp": 100, "attack": 125, "defense": 52}'),
(431, 'Glameow', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/431.png', 'Normal', 'common', '{"hp": 49, "attack": 55, "defense": 42}'),
(432, 'Purugly', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/432.png', 'Normal', 'uncommon', '{"hp": 71, "attack": 82, "defense": 64}'),
(433, 'Chingling', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/433.png', 'Psychic', 'common', '{"hp": 45, "attack": 30, "defense": 50}'),
(434, 'Stunky', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/434.png', 'Poison/Dark', 'common', '{"hp": 63, "attack": 63, "defense": 47}'),
(435, 'Skuntank', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/435.png', 'Poison/Dark', 'uncommon', '{"hp": 103, "attack": 93, "defense": 67}'),
(436, 'Bronzor', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/436.png', 'Steel/Psychic', 'common', '{"hp": 57, "attack": 24, "defense": 86}'),
(437, 'Bronzong', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/437.png', 'Steel/Psychic', 'uncommon', '{"hp": 67, "attack": 89, "defense": 116}'),
(438, 'Bonsly', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/438.png', 'Rock', 'common', '{"hp": 50, "attack": 80, "defense": 95}'),
(439, 'Mime Jr.', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/439.png', 'Psychic/Fairy', 'uncommon', '{"hp": 20, "attack": 25, "defense": 45}'),
(440, 'Happiny', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/440.png', 'Normal', 'uncommon', '{"hp": 100, "attack": 5, "defense": 5}'),
(441, 'Chatot', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/441.png', 'Normal/Flying', 'uncommon', '{"hp": 76, "attack": 65, "defense": 45}'),
(442, 'Spiritomb', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/442.png', 'Ghost/Dark', 'rare', '{"hp": 50, "attack": 92, "defense": 108}'),
(443, 'Gible', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/443.png', 'Dragon/Ground', 'rare', '{"hp": 58, "attack": 70, "defense": 45}'),
(444, 'Gabite', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/444.png', 'Dragon/Ground', 'rare', '{"hp": 68, "attack": 90, "defense": 65}'),
(445, 'Garchomp', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/445.png', 'Dragon/Ground', 'rare', '{"hp": 108, "attack": 130, "defense": 95}'),
(446, 'Munchlax', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/446.png', 'Normal', 'uncommon', '{"hp": 135, "attack": 85, "defense": 40}'),
(447, 'Riolu', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/447.png', 'Fighting', 'rare', '{"hp": 40, "attack": 70, "defense": 40}'),
(448, 'Lucario', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/448.png', 'Fighting/Steel', 'rare', '{"hp": 70, "attack": 110, "defense": 70}'),
(449, 'Hippopotas', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/449.png', 'Ground', 'common', '{"hp": 68, "attack": 72, "defense": 78}'),
(450, 'Hippowdon', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/450.png', 'Ground', 'uncommon', '{"hp": 108, "attack": 112, "defense": 118}'),
(451, 'Skorupi', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/451.png', 'Poison/Bug', 'common', '{"hp": 40, "attack": 50, "defense": 90}'),
(452, 'Drapion', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/452.png', 'Poison/Dark', 'uncommon', '{"hp": 70, "attack": 90, "defense": 110}'),
(453, 'Croagunk', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/453.png', 'Poison/Fighting', 'common', '{"hp": 48, "attack": 61, "defense": 40}'),
(454, 'Toxicroak', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/454.png', 'Poison/Fighting', 'uncommon', '{"hp": 83, "attack": 106, "defense": 65}'),
(455, 'Carnivine', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/455.png', 'Grass', 'uncommon', '{"hp": 74, "attack": 100, "defense": 72}'),
(456, 'Finneon', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/456.png', 'Water', 'common', '{"hp": 49, "attack": 49, "defense": 56}'),
(457, 'Lumineon', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/457.png', 'Water', 'uncommon', '{"hp": 69, "attack": 69, "defense": 76}'),
(458, 'Mantyke', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/458.png', 'Water/Flying', 'uncommon', '{"hp": 45, "attack": 20, "defense": 50}'),
(459, 'Snover', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/459.png', 'Grass/Ice', 'common', '{"hp": 60, "attack": 62, "defense": 50}'),
(460, 'Abomasnow', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/460.png', 'Grass/Ice', 'uncommon', '{"hp": 90, "attack": 92, "defense": 75}'),
(461, 'Weavile', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/461.png', 'Dark/Ice', 'rare', '{"hp": 70, "attack": 120, "defense": 65}'),
(462, 'Magnezone', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/462.png', 'Electric/Steel', 'rare', '{"hp": 70, "attack": 70, "defense": 115}'),
(463, 'Lickilicky', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/463.png', 'Normal', 'uncommon', '{"hp": 110, "attack": 85, "defense": 95}'),
(464, 'Rhyperior', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/464.png', 'Ground/Rock', 'rare', '{"hp": 115, "attack": 140, "defense": 130}'),
(465, 'Tangrowth', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/465.png', 'Grass', 'rare', '{"hp": 100, "attack": 100, "defense": 125}'),
(466, 'Electivire', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/466.png', 'Electric', 'rare', '{"hp": 75, "attack": 123, "defense": 67}'),
(467, 'Magmortar', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/467.png', 'Fire', 'rare', '{"hp": 75, "attack": 95, "defense": 67}'),
(468, 'Togekiss', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/468.png', 'Fairy/Flying', 'rare', '{"hp": 85, "attack": 50, "defense": 95}'),
(469, 'Yanmega', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/469.png', 'Bug/Flying', 'rare', '{"hp": 86, "attack": 76, "defense": 86}'),
(470, 'Leafeon', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/470.png', 'Grass', 'rare', '{"hp": 65, "attack": 110, "defense": 130}'),
(471, 'Glaceon', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/471.png', 'Ice', 'rare', '{"hp": 65, "attack": 60, "defense": 110}'),
(472, 'Gliscor', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/472.png', 'Ground/Flying', 'rare', '{"hp": 75, "attack": 95, "defense": 125}'),
(473, 'Mamoswine', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/473.png', 'Ice/Ground', 'rare', '{"hp": 110, "attack": 130, "defense": 80}'),
(474, 'Porygon-Z', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/474.png', 'Normal', 'rare', '{"hp": 85, "attack": 80, "defense": 70}'),
(475, 'Gallade', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/475.png', 'Psychic/Fighting', 'rare', '{"hp": 68, "attack": 125, "defense": 65}'),
(476, 'Probopass', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/476.png', 'Rock/Steel', 'uncommon', '{"hp": 60, "attack": 55, "defense": 145}'),
(477, 'Dusknoir', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/477.png', 'Ghost', 'rare', '{"hp": 45, "attack": 100, "defense": 135}'),
(478, 'Froslass', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/478.png', 'Ice/Ghost', 'rare', '{"hp": 70, "attack": 80, "defense": 70}'),
(479, 'Rotom', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/479.png', 'Electric/Ghost', 'rare', '{"hp": 50, "attack": 50, "defense": 77}'),
(480, 'Uxie', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/480.png', 'Psychic', 'legendary', '{"hp": 75, "attack": 75, "defense": 130}'),
(481, 'Mesprit', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/481.png', 'Psychic', 'legendary', '{"hp": 80, "attack": 105, "defense": 105}'),
(482, 'Azelf', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/482.png', 'Psychic', 'legendary', '{"hp": 75, "attack": 125, "defense": 70}'),
(483, 'Dialga', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/483.png', 'Steel/Dragon', 'legendary', '{"hp": 100, "attack": 120, "defense": 120}'),
(484, 'Palkia', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/484.png', 'Water/Dragon', 'legendary', '{"hp": 90, "attack": 120, "defense": 100}'),
(485, 'Heatran', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/485.png', 'Fire/Steel', 'legendary', '{"hp": 91, "attack": 90, "defense": 106}'),
(486, 'Regigigas', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/486.png', 'Normal', 'legendary', '{"hp": 110, "attack": 160, "defense": 110}'),
(487, 'Giratina', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/487.png', 'Ghost/Dragon', 'legendary', '{"hp": 150, "attack": 100, "defense": 120}'),
(488, 'Cresselia', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/488.png', 'Psychic', 'legendary', '{"hp": 120, "attack": 70, "defense": 110}'),
(489, 'Phione', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/489.png', 'Water', 'legendary', '{"hp": 80, "attack": 80, "defense": 80}'),
(490, 'Manaphy', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/490.png', 'Water', 'legendary', '{"hp": 100, "attack": 100, "defense": 100}'),
(491, 'Darkrai', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/491.png', 'Dark', 'legendary', '{"hp": 70, "attack": 90, "defense": 90}'),
(492, 'Shaymin', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/492.png', 'Grass', 'legendary', '{"hp": 100, "attack": 100, "defense": 100}'),
(493, 'Arceus', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/493.png', 'Normal', 'legendary', '{"hp": 120, "attack": 120, "defense": 120}')
ON CONFLICT (id) DO NOTHING;

-- Clean up any existing pools and reinitialize all schools with 500 unique Pokemon
DELETE FROM public.pokemon_pools;

-- Now reinitialize all school pools with 500 unique Pokemon from the expanded catalog
DO $$
DECLARE
    school_record RECORD;
    catalog_pokemon RECORD;
    pokemon_array INTEGER[];
    selected_pokemon INTEGER[];
    pool_size INTEGER := 500;
    available_count INTEGER;
BEGIN
    -- Get count of available Pokemon in catalog
    SELECT COUNT(*) INTO available_count FROM public.pokemon_catalog;
    
    -- Adjust pool size if we don't have enough Pokemon
    IF available_count < pool_size THEN
        pool_size := available_count;
    END IF;
    
    -- Loop through each school
    FOR school_record IN SELECT id FROM public.schools LOOP
        -- Get all Pokemon IDs from catalog
        SELECT ARRAY(SELECT id FROM public.pokemon_catalog ORDER BY RANDOM()) INTO pokemon_array;
        
        -- Take first 500 (or available count) Pokemon
        selected_pokemon := pokemon_array[1:pool_size];
        
        -- Insert into pokemon_pools for this school
        INSERT INTO public.pokemon_pools (school_id, pokemon_id, status)
        SELECT school_record.id, unnest(selected_pokemon), 'available';
        
        RAISE NOTICE 'Initialized school % with % Pokemon', school_record.id, pool_size;
    END LOOP;
END $$;
