// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ffhwrbrzyphuwvkkmoxd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZmaHdyYnJ6eXBodXd2a2ttb3hkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcxMzk5MjAsImV4cCI6MjA2MjcxNTkyMH0.YFje3L6o7EOaZQMQbtUc6G5i_DAFWWCGCQwK5lTc16Q";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);